import CmsNavbar from "./_components/cms-navbar";

import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AdminRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col h-screen">
          <CmsNavbar />
          {children}
        </div>
      </body>
    </html>
  );
}
